theme: jekyll-theme-minimal
title: Aravind N
logo: /Docs/MyPic.jpg
author: GitHub User
email: your-email@domain.com
LinkedIn: [![LinkedIn Badge]](linkedin.com/in/aravind-nagaraju)

github:
  is_project_page: false
