theme: jekyll-theme-minimal
title: Aravind N
logo: /Docs/MyPic.jpg
author: GitHub User
email: your-email@domain.com
LinkedIn: [![LinkedIn Badge](https://img.shields.io/badge/LinkedIn-Profile-informational?style=flat&logo=linkedin&logoColor=white&color=0D76A8)](linkedin.com/in/aravind-nagaraju)

github:
  is_project_page: false
